# Generated by Django 3.2.6 on 2023-03-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='C:\\Users\\KDFX Modes\\PycharmProjects\\Coursework_6\\skymarket\\django_media')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'custom_user',
            },
        ),
    ]
